### PR TITLE
added Win64, linux-aarch64 and ppc64le targets 

### PR DESCRIPTION
**Pull request by bmcfee**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This PR makes an attempt at fixing #28 by using the packaged CMake port in the mpg123 source.  It subsumes the currently outstanding PR #29 .

### CODE REVIEW

**Comment by bmcfee** [comment]
Ok, as far as I can tell, this all seems to be working properly now.  The CMake port only defines targets for the libraries, not the commandline app, but as noted in #28 I think that's probably fine.

I've closed out #29 as the changes in that PR are included here as well (linux aarch64 + ppc64le), and I see no reason to bump the build number twice for what's essentially just adding more platforms.

I'd really appreciate a check from @thomasfillon and/or @hbredin just to make sure I didn't do anything silly here.  Otherwise, I think this is good to go.

**Comment by bmcfee** [comment]
@conda-forge/core :wave: hoping for a quick sanity check on the build setup here.  (I know this PR hasn't been open for long, but it's continuing the work of an older PR that received no feedback either.  I don't think the other maintainers listed are likely to chime in.)

I *think* this is good to go - tests pass on all platforms, things seem to work - but I'd like an external thumbs up regarding how I went about the build here.  I am listed as a maintainer on this feedstock, but I'm not comfortable with pulling the merge trigger yet because this particular build is a little wonky due to the use of mpg123's possibly-not-quite-maintained cmake scripts on windows.  If someone could suggest a more robust test than existence of the dll/lib files, or verify that this is sufficient, I'd appreciate it.

The cmake scripts in mpg123 do not seem to properly build the command-line app, so doing an execution test is probably out of the question.

Thanks!

**Comment by dopplershift** [comment]
Seems reasonable to me.

**Comment by bmcfee** [comment]
Alright, thanks for giving it a look!  I'll merge, and in the unlikely event that something doesn't work right, the next downstream package that i'm working on (libsndfile) should detect it pretty quickly.

**Pull request merged**
