### PR TITLE
updated mpg123 to 1.29.3 + rerendered

### PR DESCRIPTION
**Pull request by bmcfee**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bmcfee** [comment]
This PR is in response to another package update https://github.com/conda-forge/libsndfile-feedstock/pull/25

**Comment by bmcfee** [comment]
This looks to me like it's working now.  It would be great to have a windows build as well, but I have zero experience in that and don't feel sufficiently adventurous to try setting it up right now.

Side question: the license.txt included in the feedstock (BSD3) did not match the package's license (LGPL).  I have left it as is for now, but should these be rectified?  Or is the feedstock license independent of the package license (which is correctly specified in meta.yml)?

**Comment by wolfv** [comment]
Yes, the feedstock license (of this recipe) is always BSD3. 

The meta.yaml and license_file specify the license of the package contents.

**Comment by wolfv** [comment]
Would you mind adding your github username to the list of maintainers in extras?

**Comment by bmcfee** [comment]
> For Windows -- I'd love to have it but I think we can try that in a dedicated follow-up PR.

Agreed.  I brought it up because this update PR is intended to support an update to another package https://github.com/conda-forge/libsndfile-feedstock/pull/25 which does have windows builds, and it would be nice if we could get that all squared away in one shot.  But I agree that this is better done in two steps.

Otherwise, thanks for the comments - I've updated accordingly and this should be ready to go when CI finishes.

**Comment by bmcfee** [comment]
Side note: this obviates #20 (I didn't realize it was open when I started this PR).  Not sure if anyone feels like back-filling prior releases #19 #18.

**Comment by bmcfee** [comment]
@thomasfillon can you give this a peep when you have a chance?  I think it's ready to go, and it's holding up some other packages.

**Comment by bmcfee** [comment]
Checking back on this one - I think it's good to go?

**Comment by bmcfee** [comment]
@hbredin @thomasfillon - checking in again, since I think this is merge-able and it's holding up some downstream updates.

**Comment by bmcfee** [comment]
Thanks!

**Pull request merged**
